name = "amaren-api"
compatibility_date = "2024-09-23"
send_metrics = true
compatibility_flags = ["nodejs_compat_v2"]
logpush = true

# Cloudflare Workers R2 buckets
# r2_buckets = [
#   { binding = "HONO_WORKERS_EXAMPLE", bucket_name = "HONO_WORKERS_EXAMPLE", preview_bucket_name = "HONO_WORKERS_EXAMPLE_PREVIEW" },
# ]

# Cloudflare Workers KV namespaces
kv_namespaces = [
  { binding = "MEMBERS", id = "e6a97041860c4c4aa63612b50aaefc1c", preview_id = "06056fd9249949d0b27b9594dea5c848" },
]

# Cron Events
[triggers]
crons = []

# Variables
[vars]

[dev]
ip = "0.0.0.0"
port = 8787
